server:
  port: 5000
spring:
  application:
    name: zuul-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    oderServiceApi:
      path: /orderservice/**
      serviceId: order-service